version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # 로컬 8080 포트를 컨테이너의 8080 포트에 연결
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-test_user}"
      POSTGRES_PASSWORD: "${POSTGRES_USER:-test_password}"
      POSTGRES_DB: "${POSTGRES_DB:-test}"
      # 도커에서 처음 postgres 설치하면서 만드는 슈퍼유저.
      # 한번 만들어진 상태면 유저 생성 더 안함. NCP에는 이런 비번 아님
    ports:
      - "5432:5432" # 로컬 5432 포트를 컨테이너의 5432 포트에 연결
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
